export const FACET_FIELDS = [
    "name_type",
    "taxonomic_status",
    "taxon_rank",
    "occurrence_status",
    "endemic",
    "establishment_means",
    "has_introduced_occurrences",
    "degree_of_establishment",
    "ffg",
    "epbc",
    "vic_advisory",
    "phylum",
    "class",
    "order",
    "family",
]
