query taxonDistributionMapQuery($id: ID!) {
  taxonConcept(id: $id) {
   id
    bioregions {
      id
      bioregion {
        type
        geometry {
          type
          coordinates
        }
        properties {
          id
          number
          regionCode
          name
          code
        }
      }
    }
    taxonName {
      id
      fullName
    }
  }
}