query matrixKeyQuery($path: String!) {
  matrixKey(path: $path) {
    id
    title
    taxonConcepts {
      ...taxonConceptFields
    }
  }
}
fragment taxonConceptFields on TaxonConcept {
  id
  taxonName {
    ...taxonNameFields
  }
}
fragment taxonNameFields on TaxonName {
  id
  fullName
  authorship
}