query MultiAccessKeyQuery($id: ID!) {
  multiAccessKey(id: $id) {
    id
    title
    description
    featureGroups {
      id
      type
      name
      description
      children {
        id
        name
      }
    }
    features {
      id
      type
      featureType
      name
      description
      states {
        id
        name
        description
      }
    }
  }
}