query ReferenceAutocompleteQuery($q: String!) {
  suggestions: referenceAutocomplete(q: $q) {
    id
    quickRef
    author {
      id
      name
    }
    publicationYear
    referenceStringHtml
  }
}
