#import "~/graphql/fragments/paginatorInfoFields.gql"

query taxonConceptImagesQuery($id: ID!, $first: Int = 24, $page: Int = 1) {
  taxonConceptImages(taxonConceptId: $id, first: $first, page: $page) {
    data {
      id
      previewUrl
      thumbnailUrl
      highestResUrl
      w: pixelXDimension
      h: pixelYDimension
      caption
      creationDate
      creator
      license
      copyrightOwner
      subtype
    }
    paginatorInfo {
      ...paginatorInfoFields
    }
  }
}
