query taxonConceptSpecimenImagesQuery(
  $id: ID!
  $first: Int = 24
  $page: Int = 1
) {
  taxonConceptSpecimenImages(taxonConceptId: $id, first: $first, page: $page) {
    data {
      id
      alaImageUuid
      thumbnailUrl
      catalogNumber
      title
      caption
    }
    paginatorInfo {
      ...paginatorInfoFields
    }
  }
}
fragment paginatorInfoFields on PaginatorInfo {
  count
  total
  perPage
  firstItem
  currentPage
  lastPage
  hasMorePages
}
