query taxonOccurrencesAtPointQuery(
  $taxonConceptId: ID!
  $latitude: Float!
  $longitude: Float!
) {
  taxonOccurrencesAtPoint(
    taxonConceptId: $taxonConceptId
    latitude: $latitude
    longitude: $longitude
    first: 500
  ) {
    paginatorInfo {
      total
      perPage
      currentPage
    }
    data {
      properties {
        dataSource
        uuid
        scientificName
        catalogNumber
        speciesName
        occurrenceStatus
        establishmentMeans
      }
    }
  }
}
