query taxonConceptQuery($id: ID!) {
  taxonConcept(id: $id) {
    id
    taxonName {
      id
      fullName
      authorship
      publishedIn {
        id
        referenceType
        title
        publicationYear
        volume
        pages
        quickRef
        referenceStringHtml
      }
      apniName {
        id
        apniNumber
      }
    }
    accordingTo {
      id
      quickRef
      referenceStringHtml
      author {
        id
        name
      }
      publicationYear
    }
    publicationStatus
    acceptedConcept {
      id
      taxonName {
        id
        fullName
        authorship
      }
    }
    synonymUsages {
      id
      taxonName {
        id
        fullName
        authorship
      }
    }
    misapplications {
      id
      taxonName {
        id
        fullName
        authorship
      }
      accordingTo {
        id
        title
      }
    }
    taxonomicStatus
    occurrenceStatus
    endemic
    establishmentMeans
    degreeOfEstablishment
    hasIntroducedOccurrences
    epbc
    ffg
    remarks

    createdBy {
      name
    }
    createdAt
    modifiedBy {
      name
    }
    updatedAt
    version
    heroImage {
      thumbnailUrl
      previewUrl
    }
    hasSpecimenImages

    mapLinks {
      profileMap
      distributionMap
      mapSource
    }

    preferredVernacularName {
      id
      name
    }

    currentProfile {
      id
      profile
      source {
        id
        referenceStringHtml
      }
      creator {
        lastName
        firstName
      }
      created
      updatedBy {
        lastName
        firstName
      }
      modified

    }
    taxonTreeDefItem {
      id
      name
      rankId
    }
    taxonRank
    parent {
      id
      taxonName {
        id
        fullName
        authorship
      }
    }
    children {
      id
      taxonName {
        id
        fullName
        authorship
      }
      taxonTreeDefItem {
        id
        name
        rankId
      }
    }
    siblings {
      id
      taxonName {
        id
        fullName
        authorship
      }
    }
    higherClassification {
      id
      taxonName {
        id
        fullName
        authorship
      }
      taxonTreeDefItem {
        id
        name
        rankId
      }
    }
    identificationKeys {
      id
      title
      taxonomicScope
      geographicScope
    }
    matrixKeys {
      id
      title
      relativePath
    }
    references {
      id
      reference {
        id
        referenceStringHtml
      }
    }
    floraLinks {
      id
      flora
      url
      icon
      sortOrder
    }
    changes {
      id
      to {
        id
        taxonName {
          id
          fullName
          authorship
        }
      }
      changeType
      changeSource {
        quickRef
      }
      createdBy {
        name
      }
      createdAt
    }
    vernacularNames {
      id
      name
      isPreferred
      nameUsage
    }
  }
}
