query taxonConceptLocalGovernmentAreasQuery($taxonConceptId: ID!) {
  taxonConceptLocalGovernmentAreas(taxonConceptId: $taxonConceptId) {
    id
    localGovernmentAreaName
    occurrenceStatus
    establishmentMeans
    degreeOfEstablishment
  }
}
