query taxonConceptBioregionsQuery($taxonConceptId: ID!) {
  taxonConceptBioregions(taxonConceptId: $taxonConceptId) {
    id
    bioregionName
    bioregionCode
    occurrenceStatus
    establishmentMeans
  }
}
