query taxonConceptQuery($id: ID!) {
  taxonConcept(id: $id) {
    id

    taxonName {
      id
      fullName
      authorship
    }
    taxonTreeDefItem {
      rankId
      id
      name
    }
    parent {
      id

      taxonName {
        id
        fullName
        authorship
      }
    }
    children {
      id

      taxonName {
        id
        fullName
        authorship
      }
      taxonTreeDefItem {
        id
        name
        rankId
      }
    }
    siblings {
      id

      taxonName {
        id
        fullName
        authorship
      }
    }
    higherClassification {
      id
      depth
      taxonConcept {
        id

        taxonName {
          id
          fullName
          authorship
        }
        taxonTreeDefItem {
          id
          name
          rankId
        }
      }
    }
  }
}
