query TaxonConceptCatchmentsQuery($taxonConceptId: ID!) {
    taxonConceptCatchments(taxonConceptId: $taxonConceptId) {
        id
        catchmentName
        occurrenceStatus
        establishmentMeans
        degreeOfEstablishment
    }
}