query taxonConceptParkReservesQuery($taxonConceptId: ID!) {
  taxonConceptParkReserves(taxonConceptId: $taxonConceptId) {
    id
    parkReserveName
    parkReserveAreaType
    occurrenceStatus
    establishmentMeans
    degreeOfEstablishment
  }
}
