query taxonConceptLocalGovernmentAreasQuery($taxonConceptId: ID!) {
  taxonConceptLocalGovernmentAreas(taxonConceptId: $taxonConceptId) {
    id
    localGovernmentAreaName
    localGovernmentAreaAbbreviatedName
    occurrenceStatus
    establishmentMeans
  }
}
