#import "~/graphql/fragments/paginatorInfoFields.gql"

query taxonConceptSpecimenImagesQuery(
  $id: ID!
  $first: Int = 24
  $page: Int = 1
) {
  taxonConcept(id: $id) {
    id
    taxonName {
      id
      fullName
    }
    specimenImages(first: $first, page: $page) {
      data {
        id
        thumbnailUrl
        alaImageUuid
        caption
      }
      paginatorInfo {
        ...paginatorInfoFields
      }
    }
  }
}
