query taxonOccurrencesAtPointQuery(
  $taxonConceptId: ID!
  $latitude: Float!
  $longitude: Float!
) {
  taxonOccurrencesAtPoint(
    taxonConceptId: $taxonConceptId
    latitude: $latitude
    longitude: $longitude
    first: 500
  ) {
    paginatorInfo {
      total
      perPage
      currentPage
    }
    data {
      properties {
        uuid
        dataSource
        collection
        catalogNumber
        recordedBy
        recordNumber
        eventDate
        scientificName
        occurrenceStatus
        establishmentMeans
        degreeOfEstablishment
      }
    }
  }
}
