#import "~/graphql/fragments/taxonConceptFields.gql"

query taxonConceptQuery($id: ID!) {
  taxonConcept(id: $id) {
    id
    taxonName {
      id
      fullName
      authorship
      publishedIn {
        id
        referenceType
        title
        publicationYear
        volume
        pages
        quickRef
        referenceStringHtml
      }
      apniName {
        id
        apniNumber
      }
    }
    accordingTo {
      id
      quickRef
      referenceStringHtml
    }
    publicationStatus
    acceptedConcept {
      ...taxonConceptFields
    }
    synonymUsages {
      ...taxonConceptFields
    }
    misapplications {
      ...taxonConceptFields
      accordingTo {
        id
        title
      }
    }
    taxonomicStatus
    occurrenceStatus
    endemic
    establishmentMeans
    degreeOfEstablishment
    epbc
    ffg
    vicAdvisory

    createdBy {
      name
    }
    createdAt
    modifiedBy {
      name
    }
    updatedAt
    version
    heroImage {
      thumbnailUrl
      previewUrl
    }
    hasSpecimenImages

    mapLinks {
      profileMap
      distributionMap
      mapSource
    }

    preferredVernacularName {
      id
      name
    }

    currentProfile {
      id
      profile
      source {
        id
        referenceStringHtml
      }
      creator {
        lastName
        firstName
      }
      created
      updatedBy {
        lastName
        firstName
      }
      modified

    }
    taxonTreeDefItem {
      id
      name
      rankId
    }
    parent {
      id

      taxonName {
        id
        fullName
        authorship
      }
    }
    children {
      ...taxonConceptFields
      taxonTreeDefItem {
        id
        name
        rankId
      }
    }
    siblings {
      ...taxonConceptFields
    }
    higherClassification {
      ...taxonConceptFields
      taxonTreeDefItem {
        id
        name
        rankId
      }
    }
    identificationKeys {
      id
      title
      taxonomicScope
      geographicScope
    }
    matrixKeys {
      id
      title
      relativePath
    }
    references {
      id
      reference {
        id
        referenceStringHtml
      }
    }
    floraLinks {
      id
      flora
      url
      icon
      sortOrder
    }
  }
}
