#import "~/graphql/fragments/taxonConceptFields.gql"

query taxonConceptQuery($id: ID!) {
  taxonConcept(id: $id) {
    id
    taxonName {
      id
      fullName
      authorship
      protologue {
        id
        title
        publicationYear
        volume
        pages
      }
    }
    acceptedConcept {
      ...taxonConceptFields
    }
    synonymUsages {
      ...taxonConceptFields
    }
    misapplications {
      ...taxonConceptFields
      accordingTo {
        id
        title
      }
    }
    taxonomicStatus
    occurrenceStatus
    establishmentMeans

    createdBy {
      name
    }
    createdAt
    modifiedBy {
      name
    }
    updatedAt
    version
    heroImage {
      thumbnailUrl
      previewUrl
    }
    hasSpecimenImages

    mapLinks {
      profileMap
      distributionMap
      mapSource
    }

    preferredVernacularName {
      id
      name
    }

    currentProfile {
      profile
    }
    taxonTreeDefItem {
      id
      name
      rankId
    }
    parent {
      id

      taxonName {
        id
        fullName
        authorship
      }
    }
    children {
      ...taxonConceptFields
      taxonTreeDefItem {
        id
        name
        rankId
      }
    }
    siblings {
      ...taxonConceptFields
    }
    higherClassification {
      id
      depth
      taxonConcept {
        ...taxonConceptFields
        taxonTreeDefItem {
          id
          name
          rankId
        }
      }
    }

    identificationKeys {
      id
      title
      taxonomicScope
      geographicScope
    }
  }
}
