query taxonClassificationQuery($id: ID!) {
  taxonConcept(id: $id) {
    ...taxonConceptFields
    taxonTreeDefItem {
      rankId
      id
      name
    }
    parent {
      ...taxonConceptFields
    }
    children {
      ...taxonConceptFields
      taxonTreeDefItem {
        id
        name
        rankId
      }
    }
    siblings {
      ...taxonConceptFields
    }
    higherClassification {
      ...taxonConceptFields
      taxonTreeDefItem {
        id
        name
        rankId
      }
    }
  }
}
fragment taxonConceptFields on TaxonConcept {
  id
  taxonName {
    ...taxonNameFields
  }
}
fragment taxonNameFields on TaxonName {
  id
  fullName
  authorship
}