query searchQuery($input: SearchInput!) {
  search(input: $input) {
    docs{
      id
      family
      taxonRank
      vernacularName
      scientificName
      scientificNameAuthorship
    }
    meta {
      params {
        q
        fq
        fl
        rows 
      }
      pagination{
        lastPage
        total
        currentPage
      }
    }
    facetFields{
      fieldName
      facets{
        value
        count
        fq
      }
    }
  }
}
