query taxonConceptQuery($id: UUID!,$imagesPage:Int,$specimenImagesPage:Int) {
  taxonConceptByGUID(guid: $id) {
    id
    guid
    mapLinks{
      profileMap
			distributionMap
      mapSource
    }
    bioregions{
      id
      occurrenceStatus{
        name
      }
      establishmentMeans{name}
      bioregion{
        type
        properties{
          # region
          subregion
        }
      }
    }
    preferredVernacularName{
      id
      name
    }
    createdBy {
      name
    }
    modifiedBy {
      name
    }
    createdAt
    updatedAt
    version
    heroImage {
      thumbnailUrl
      previewUrl
    }
    images(page:$imagesPage,first:24){
      data {
        id
        previewUrl
        thumbnailUrl
        assetCreationDate
        caption
        creator
        license
        rights
        subtype
			}
      paginatorInfo{
        count
        currentPage
        hasMorePages
        total
      }
    }
    specimenImages(page:$specimenImagesPage,first:24){
       data {
        id
        thumbnailUrl
        alaImageUuid
        caption
			}
      paginatorInfo{
        count
        currentPage
        hasMorePages
        total
      }
    }

    currentProfile {
      profile
    }
    taxonName {
      id
      fullName
      authorship
      protologue{
        id
        title
        publicationYear
        volume
        pages
        
      }
    }
    taxonTreeDefItem {
      id
      name
      rankId
    }
    parent {
      id
      guid
      taxonName {
        id
        fullName
        authorship
      }
    }
    children {
      id
      guid
      taxonName {
        id
        fullName
        authorship
      }
      taxonTreeDefItem {
        id
        name
        rankId
      }
    }
    siblings {
      id
      guid
      taxonName {
        id
        fullName
        authorship
      }
    }
    higherClassification {
      id
      depth
      taxonConcept {
        id
        guid
        taxonName {
          id
          fullName
          authorship
        }
        taxonTreeDefItem {
          id
          name
          rankId
        }
      }
    }
    taxonomicStatus {
      id
      name
    }
    occurrenceStatus {
      id
      name
    }
    establishmentMeans {
      id
      name
    }
  }
}
